---
- name: Install Ansible on the Jenkins server
  hosts: jenkinsserver
  become: yes
  tasks:
    - name: Install ansible
      apt:
        name: ansible
        update_cache: yes
        cache_valid_time: 3600
        state: latest
