---
- name: Install lighttpd and config services on the web server
  hosts: webserver 
  become: yes
  tasks:
    - name: Update apt repositories
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Install lighttpd via apt
      apt:
       name: lighttpd
    
    - name: Restart and enable service
      systemd:
        name: lighttpd
        enabled: yes
        state: restarted