---
- name: Install lighttpd and config services on the web server
  hosts: webserver
  become: yes
  tasks:
    - name: Install lighttpd via apt
      apt:
        name: lighttpd
        update_cache: yes
        cache_valid_time: 3600

    - name: Enable and restart the lighttpd service
      systemd:
        name: lighttpd
        enabled: yes
        state: restarted
