---
- name: Install Jenskins on the Jenkins server
  hosts: jenkinsserver
  become: yes
  tasks:
  - name: Install some Jenkins prerequisities
    apt:
      update_cache: yes
      cache_valid_time: 3600
      install_recommends: no
      pkg:
        - wget
        - curl
        - default-jre
        - gnupg2
        - git

  - name: Add a Jenkins signing key
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present

  - name: Add download repo for Jenkins
    become: true
    shell: sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

  - name: Install Jenkins
    apt:
      name: jenkins
      state: present
      update_cache: yes
      cache_valid_time: 3600

  - name: Start Jenkins service and enable on boot
    systemd:
      name: jenkins
      state: restarted
      enabled: yes

  - name: Pause and wait for jenkins to start
    pause:
      seconds: 15

  - name: Check if the file initialAdminPassword exists
    stat:
      path: /var/lib/jenkins/secrets/initialAdminPassword
    register: pwd_file_exists

  - name: Init password jenkin
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: result
    changed_when: false
    when: pwd_file_exists.stat.exists

  - name: Print init password Jenkins
    debug:
      var: result.stdout
    when: pwd_file_exists.stat.exists